alias vi='vim'

alias zshrc='vi ~/.zshrc'
alias srczshrc='source ~/.zshrc'

alias bashrc='vi ~/.bashrc'
alias srcbashrc='source ~/.bashrc'

alias ls='ls --color=auto'
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

alias gst='git status'
alias ga='git add'
alias gc='git commit --verbose'
alias gcm='git commit --amend --verbose'
alias gd='git diff'
alias gp='git push'
alias gl='git pull'
alias gf='git fetch'
alias gsl='git log --oneline --max-count=20'
alias gsla='git log --oneline --max-count=20 --all'
alias gslg='git log --oneline --max-count=20 --graph'
alias gslag='git log --oneline --max-count=20 --all --graph'
